/**
 * Composition generation: turning a persona into an `agent.cordis.yml` entry
 * list. A base preset's composition is copied VERBATIM (text splice, not a
 * YAML parse — the harness's dialect carries `!!js` expressions and template
 * strings that must round-trip untouched) with the persona row replaced by a
 * neutral one. With no base composition available, the materialized preset is
 * a bare neutral persona row: the agent keeps the deployment's global layer
 * but adds no preset-scoped tools, which is the documented fallback.
 *
 * The persona row mounts the persona package once (`@deepseek-ai/dsh-persona`)
 * with empty text, so the materialized preset contributes no persona of its
 * own. The live persona comes from the `persona:policy` prompt section, which
 * resolves the session's persona from the runtime catalog — never from text
 * spliced into the preset. That decoupling is what makes a mid-conversation
 * persona switch possible: switching changes session state, never the mounted
 * composition (which is blank-session-locked).
 * @module agents/compose
 */

import type { Persona } from "./persona.js";

/** The plugin id that owns a preset's persona row. */
export const PERSONA_PLUGIN = "@deepseek-ai/dsh-persona";

/** The neutral persona row every materialized preset mounts. */
function neutralPersonaRow(): string {
  return ["- id: persona", `  name: '${PERSONA_PLUGIN}'`, "  config:", "    text: ''"].join("\n");
}

/**
 * Splice the neutral persona row into a base composition's entry list,
 * replacing the base's persona row (identified by `id: persona`). The base
 * text is otherwise untouched. A composition without a persona row gets the
 * neutral row prepended. The result is always exactly one persona row.
 * @param composition - the base composition text, as stored.
 */
export function splicePersona(composition: string): string {
  const marker = "- id: persona\n";
  const start = composition.indexOf(marker);
  if (start === -1) return `${neutralPersonaRow()}\n\n${composition}`;
  const nextRow = composition.indexOf("\n- id: ", start + marker.length);
  const end = nextRow === -1 ? composition.length : nextRow;
  return composition.slice(0, start) + neutralPersonaRow() + "\n\n" + composition.slice(end);
}

/**
 * The full `agent.cordis.yml` text for a materialized preset. With a base
 * composition the neutral persona row is spliced in; without one, the entry
 * list is the neutral row alone.
 * @param baseComposition - the base preset's composition, when reachable.
 */
export function composeComposition(baseComposition: string | undefined): string {
  return baseComposition !== undefined
    ? splicePersona(baseComposition)
    : `${neutralPersonaRow()}\n`;
}

/** Quote a metadata value as a YAML double-quoted scalar. */
function quoted(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

/**
 * The `preset.yml` display metadata for a persona: name and description, each
 * omitted when absent so the picker falls back to the id.
 */
export function composeMetadata(persona: Persona): string {
  const lines: string[] = [];
  if (persona.name !== undefined) lines.push(`name: ${quoted(persona.name)}`);
  if (persona.description !== undefined) lines.push(`description: ${quoted(persona.description)}`);
  return lines.length === 0
    ? "# auto-generated by agents; no display metadata\n"
    : lines.join("\n") + "\n";
}
