import type { PackDefinition, PluginDefinition, ProfileDefinition } from "./types.js";

export const plugins: readonly PluginDefinition[] = [
  {
    id: "stack.core.composition",
    version: "0.1.0",
    description: "Stack composition metadata and profile assembly.",
    provides: ["stack.composition"],
  },
  {
    id: "stack.ui.sidebar-shell",
    version: "0.1.0",
    description:
      "Canonical Stack sidebar shell with configurable branding and new-conversation controls.",
    dependencies: [{ plugin: "stack.core.composition", kind: "required" }],
    provides: ["ui.sidebar-shell"],
  },
  {
    id: "stack.ui.profile",
    version: "0.1.0",
    description: "Profile selector and Profiles settings page.",
    dependencies: [{ plugin: "stack.ui.sidebar-shell", kind: "required" }],
    provides: ["ui.profile-selector", "ui.profile-settings"],
  },
  {
    id: "stack.ui.sidebar-settings",
    version: "0.1.0",
    description: "Sidebar preferences for branding and new-conversation visibility.",
    dependencies: [{ plugin: "stack.ui.sidebar-shell", kind: "required" }],
    provides: ["ui.sidebar-settings"],
  },
  {
    id: "stack.ui.icons",
    version: "0.1.0",
    description: "Canonical file, folder and language icon resolution.",
    dependencies: [{ plugin: "stack.core.composition", kind: "required" }],
    provides: ["ui.icons"],
  },
  {
    id: "stack.ui.icons.vscode",
    version: "0.1.0",
    description: "VS Code icon-theme format support and file/folder associations.",
    dependencies: [{ plugin: "stack.ui.icons", kind: "required" }],
    provides: ["ui.icons.vscode"],
  },
  {
    id: "stack.ui.skin.host",
    version: "0.1.0",
    description: "Active-skin host that fills the DSH brand slots without duplicating the sidebar.",
    dependencies: [{ plugin: "stack.ui.sidebar-shell", kind: "required" }],
    provides: ["ui.skin-host"],
  },
  {
    id: "stack.ui.skin.deepseek",
    version: "0.1.0",
    description: "DeepSeek branded UI skin.",
    dependencies: [{ plugin: "stack.ui.skin.host", kind: "required" }],
    provides: ["ui.skin.deepseek"],
  },
  {
    id: "stack.ui.skin.claude",
    version: "0.1.0",
    description: "Claude branded UI skin.",
    dependencies: [{ plugin: "stack.ui.skin.host", kind: "required" }],
    provides: ["ui.skin.claude"],
  },
  {
    id: "stack.ui.skin.codex",
    version: "0.1.0",
    description: "Codex branded UI skin.",
    dependencies: [{ plugin: "stack.ui.skin.host", kind: "required" }],
    provides: ["ui.skin.codex"],
  },
  {
    id: "stack.ui.skin.settings",
    version: "0.1.0",
    description: "Skin selection settings page.",
    dependencies: [{ plugin: "stack.ui.skin.host", kind: "required" }],
    provides: ["ui.skin-settings"],
  },
  {
    id: "stack.workspace.tabs",
    version: "0.1.0",
    description: "Workspace tab lifecycle, persistence and multi-pane state.",
    dependencies: [{ plugin: "stack.core.composition", kind: "required" }],
    provides: ["workspace.tabs"],
  },
  {
    id: "stack.workspace.files",
    version: "0.1.0",
    description: "Filesystem browser semantics, file rows and context actions.",
    dependencies: [
      { plugin: "stack.workspace.tabs", kind: "required" },
      { plugin: "stack.ui.icons", kind: "required" },
    ],
    provides: ["workspace.files"],
  },
  {
    id: "stack.planning.core",
    version: "0.1.0",
    description: "Shared project and task planning domain.",
    dependencies: [{ plugin: "stack.core.composition", kind: "required" }],
    provides: ["planning.core"],
  },
  {
    id: "stack.integration.github",
    version: "0.1.0",
    description: "GitHub API and repository integration boundary.",
    dependencies: [{ plugin: "stack.planning.core", kind: "optional" }],
    provides: ["integration.github"],
  },
  {
    id: "stack.integration.github-projects",
    version: "0.1.0",
    description: "GitHub Projects planning-board integration.",
    dependencies: [
      { plugin: "stack.planning.core", kind: "required" },
      { plugin: "stack.integration.github", kind: "required" },
    ],
    provides: ["integration.github-projects"],
  },
  {
    id: "stack.integration.trello",
    version: "0.1.0",
    description: "Trello board integration.",
    dependencies: [{ plugin: "stack.planning.core", kind: "required" }],
    provides: ["integration.trello"],
  },
  {
    id: "stack.coding.darkfactory",
    version: "0.1.0",
    description: "DarkFactory-derived coding automation and repository control plane.",
    dependencies: [
      { plugin: "stack.planning.core", kind: "required" },
      { plugin: "stack.integration.github", kind: "required" },
    ],
    provides: ["coding.automation", "repository.control-plane"],
  },
  {
    id: "stack.trading.market-data",
    version: "0.1.0",
    description: "Trading market data capability.",
    dependencies: [{ plugin: "stack.core.composition", kind: "required" }],
    provides: ["trading.market-data"],
  },
  {
    id: "stack.trading.research",
    version: "0.1.0",
    description: "Trading research and strategy-analysis capability.",
    dependencies: [{ plugin: "stack.trading.market-data", kind: "required" }],
    provides: ["trading.research"],
  },
  {
    id: "stack.trading.backtest",
    version: "0.1.0",
    description: "Deterministic trading backtesting and evaluation.",
    dependencies: [{ plugin: "stack.trading.research", kind: "required" }],
    provides: ["trading.backtest"],
  },
  {
    id: "stack.trading.optimizer",
    version: "0.1.0",
    description: "Trading parameter search and strategy optimization.",
    dependencies: [{ plugin: "stack.trading.backtest", kind: "required" }],
    provides: ["trading.optimizer"],
  },
  {
    id: "stack.skyblock.hypixel",
    version: "0.1.0",
    description: "Hypixel API and SkyBlock data integration.",
    provides: ["skyblock.hypixel"],
  },
  {
    id: "stack.skyblock.domain",
    version: "0.1.0",
    description: "SkyBlock deterministic domain model and calculations.",
    dependencies: [{ plugin: "stack.skyblock.hypixel", kind: "required" }],
    provides: ["skyblock.domain"],
  },
  {
    id: "stack.skyblock.objectives",
    version: "0.1.0",
    description: "SkyBlock objectives and deterministic planning state.",
    dependencies: [
      { plugin: "stack.skyblock.domain", kind: "required" },
      { plugin: "stack.planning.core", kind: "required" },
    ],
    provides: ["skyblock.objectives"],
  },
];

export const packs: readonly PackDefinition[] = [
  {
    id: "stack.workspace",
    version: "0.1.0",
    description: "Shared workspace chrome, skins, file interaction and tabs.",
    plugins: [
      "stack.core.composition",
      "stack.ui.sidebar-shell",
      "stack.ui.profile",
      "stack.ui.sidebar-settings",
      "stack.ui.icons",
      "stack.ui.icons.vscode",
      "stack.ui.skin.host",
      "stack.ui.skin.deepseek",
      "stack.ui.skin.claude",
      "stack.ui.skin.codex",
      "stack.ui.skin.settings",
      "stack.workspace.tabs",
      "stack.workspace.files",
    ],
  },
  {
    id: "stack.planning",
    version: "0.1.0",
    description: "Planning plus external project-board integrations.",
    plugins: [
      "stack.planning.core",
      "stack.integration.github",
      "stack.integration.github-projects",
      "stack.integration.trello",
    ],
  },
  {
    id: "stack.coding",
    version: "0.1.0",
    description: "Software engineering and DarkFactory-derived automation.",
    plugins: ["stack.coding.darkfactory"],
  },
  {
    id: "stack.trading",
    version: "0.1.0",
    description: "Quantitative research and trading capabilities.",
    plugins: [
      "stack.trading.market-data",
      "stack.trading.research",
      "stack.trading.backtest",
      "stack.trading.optimizer",
    ],
  },
  {
    id: "stack.skyblock",
    version: "0.1.0",
    description: "Hypixel SkyBlock domain and planning capabilities.",
    plugins: ["stack.skyblock.hypixel", "stack.skyblock.domain", "stack.skyblock.objectives"],
  },
];

export const profiles: readonly ProfileDefinition[] = [
  {
    id: "stack.profile.default",
    version: "0.1.0",
    description: "General-purpose integrated DSH Stack environment.",
    packs: ["stack.workspace", "stack.planning"],
  },
  {
    id: "stack.profile.coding",
    version: "0.1.0",
    description: "Software-engineering focused DSH Stack environment.",
    packs: ["stack.workspace", "stack.planning", "stack.coding"],
  },
  {
    id: "stack.profile.trading",
    version: "0.1.0",
    description: "Quantitative trading and research environment.",
    packs: ["stack.workspace", "stack.trading"],
  },
  {
    id: "stack.profile.skyblock",
    version: "0.1.0",
    description: "Hypixel SkyBlock domain and planning environment.",
    packs: ["stack.workspace", "stack.planning", "stack.skyblock"],
  },
];
